### ISSUE TITLE
Increase functionality of dump action

### ISSUE THREAD

**Issue by nikita-klsh** [gazprom-neft/SeismicPro#32]
1. Implement the `mode='a'` of `dump(fmt='segy')` action. In this case instead of creating lots of small segys during the pipeline, append batch traces to the single preallocated segy.

2. `batch.dump` functionality are currently not available in `seismic_batch.dump`

**Comment by dpodvyaznikov** [comment]
I believe this issue is irrelevant due to updates in `refator` branch. Should we close it? @nikita-klsh @alexandrkuvaev

**Comment by alexanderkuvaev** [comment]
Closed as stale, reopen later if needed
