### ISSUE TITLE
fix plotters

### ISSUE THREAD

**Issue by anton-br** [gazprom-neft/SeismicPro#39]
do smth with our plotters please
* add default kwargs to `seismic_plot`
* sometimes seismic_plot draw blank line on the right side
* unify saving procedure
* anything more you want to change

**Comment by anton-br** [comment]
add new labels for axis: `time` for y axis and `offset` for x axis.

**Comment by a-arefina** [comment]
add new parameter `y_ticks` with default value `'time'` and alternative value `'samples'`. You can also make it boolean, if you come up with a suitable name :wink:

**Comment by nikita-klsh** [comment]
> add new labels for axis: `time` for y axis and `offset` for x axis.

In seismic software when plotting the gather, by default the X-axis ticks are trace indices (like we plot it now). And optionally you can specify X-axis ticks to be Offset, TraceNumber etc.

**Comment by anton-br** [comment]
Parameter `pts` in `seismic_plot` has worng docs right now. It's size should be (2, N), not (n, ). 

Also. `pts` is missed if we call in from `batch.seismic_plot`

**Comment by alexanderkuvaev** [comment]
Already implemented in `Gather.plot`
