### ISSUE TITLE
From The Beginning

### ISSUE THREAD

**Issue by walid-osman** [gazprom-neft/SeismicPro#52]
dear all,

if I want to start this project from scratch, how to start, is there any manual to use where to get the data-set.

Regards,
Walid

**Comment by dpodvyaznikov** [comment]
Hi, @walid-osman !

I'd recommend to go through our [tutorials](https://github.com/gazprom-neft/SeismicPro/tree/master/tutorials) first, to get the general understanding of the SeismicPro's structure and functionality.

Then you can move to [models](https://github.com/gazprom-neft/SeismicPro/tree/master/models) section and see how the models are trained.  In most cases, if you have the proper data and labels, you'll just need to replace the paths in the notebooks to train your own model.

Regarding the data: we do not provide the datasets and labels right now, but you can use any open-sourced dataset or create your own to reproduce the results.
