### ISSUE TITLE
Tutorial Link is broken

### ISSUE THREAD

**Issue by CeRBeR666** [gazprom-neft/SeismicPro#74]
Hello,
I want to help you with your work, but the tutorial links are broken.
Could you please give the correct address?
Thank you.

**Comment by anton-br** [comment]
Hi, thank you for your attention to our work. Unfortunately, tutorials are under development, but you can take a look at the raw version [here](https://github.com/gazprom-neft/SeismicPro/tree/tutorials/tutorials).

Moreover, we will be happy to hear any feedback about them here or in the corresponding [pull request](https://github.com/gazprom-neft/SeismicPro/pull/59).

**Comment by CeRBeR666** [comment]
Thank you very much for your quick reply.
I hope I can contribute.
See you
