### ISSUE TITLE
Tutorial link 404

### ISSUE THREAD

**Issue by RichardScottOZ** [gazprom-neft/SeismicPro#83]
https://github.com/gazprom-neft/SeismicPro/blob/master/tutorials

In the README

**Comment by anton-br** [comment]
Hello, Richard!
Thanks for your attention to our library. Tutorials, for now, are in development and will be released soon.
You can find the raw version in the [`tutorials`](https://github.com/gazprom-neft/SeismicPro/tree/tutorials/tutorials) branch.

Do not hesitate to ask any questions

**Comment by RichardScottOZ** [comment]
Thanks!
